### ISSUE TITLE
server端sh start.sh失败

### ISSUE THREAD

**Issue by tinglany** [FISCO-BCOS/fisco-bcos-browser#1]
[root@localhost fisco-bcos-browser]# gradle clean
:clean

BUILD SUCCESSFUL

Total time: 4.176 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html
[root@localhost fisco-bcos-browser]#
[root@localhost fisco-bcos-browser]#
[root@localhost fisco-bcos-browser]# ls
build.gradle       libs        README.md  serverStatus.sh  start.sh
fisco-bcos-server  mysql.sock  script     src              stop.sh
[root@localhost fisco-bcos-browser]#
[root@localhost fisco-bcos-browser]#
[root@localhost fisco-bcos-browser]# gradle build
:compileJava
:processResources
:classes
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test
:check
:build

BUILD SUCCESSFUL
Total time: 6.991 secs
This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14/userguide/gradle_daemon.html
[root@localhost fisco-bcos-browser]# ls
build         fisco-bcos-server  mysql.sock  script           src       stop.sh
build.gradle  libs               README.md   serverStatus.sh  start.sh
[root@localhost fisco-bcos-browser]# sh start.sh
===============================================================================================
Starting org.bcos.browser.service.Main ...Error: Could not find or load main class org.bcos.browser.service.Main
[Failed]
===============================================================================================

**Comment by cloudwindworld** [comment]
编译出错了吗？用反编译工具，确认一下org.bcos.browser.service.Main 这个类是否存在呢

**Comment by JimmyShi22** [comment]
build成功后，需要进到生成的fisco-bcos-server下，再执行start.sh。而不是执行外层文件夹的start.sh。

# server/fisco-bcos-browser目录下
cd fisco-bcos-server/ #注意：需要进到生成的文件夹fisco-bcos-server中，再执行start.sh脚本
sh start.sh		
#若需要停止server服务
sh stop.sh
