### ISSUE TITLE
首页当前块高正常增加，交易总量却不变

### ISSUE THREAD

**Issue by pengbs** [FISCO-BCOS/fisco-bcos-browser#11]
您好，我部署evidenceSample后能正常运行，发现首页`当前块高`是正常增加，但是`交易总量`却一直不变
![tim 20180424152801](https://user-images.githubusercontent.com/13148394/39172363-1b29419c-47d4-11e8-82b0-eaffe4d176c1.png)

**Comment by JimmyShi22** [comment]
设置了出空快？

**Comment by hellolyf** [comment]
你好，请问在哪设置出空块？
