### ISSUE TITLE
区块链浏览器交易状态的问题

### ISSUE THREAD

**Issue by Automannn** [FISCO-BCOS/fisco-bcos-browser#131]
区块链浏览器查看交易详情的时候，交易状态是一个状态码，不够直观。如图:
![image](https://user-images.githubusercontent.com/27360668/73712260-7be25480-4744-11ea-836d-adbcbfb24fdb.png)
如果能够在区块交易的下方单开一列，显著的标识当前交易是什么状态(如：成功则绿色，失败则红色警告等)，点开交易详情，交易状态显示状态，而不显示状态码，就更好了。

**Comment by mingzhenliu** [comment]
非常感谢您的建议，我们后续版本优化下
