### ISSUE TITLE
query fail:System abnormality

### ISSUE THREAD

**Issue by ymy0** [FISCO-BCOS/fisco-bcos-browser#15]
请问mysql的ip地址设为多少啊？刚搭建的区块链浏览器怎么可能有记录呢？这个记录记录的是mysql中存储的数据吗？刚创建的mysql又怎么会有数据呢？

**Comment by JimmyShi22** [comment]
区块链浏览器部署前，首先需确认部署了mysql的环境。之后再部署浏览器时，执行deploy_browser.sh时，会根据配置信息，用配置的账号，密码登录到mysql上，自动建数据库，建表。
``` shell
#deploy_browser.sh
######################  参数配置  ######################

userName="test"  #需要创建的数据库用户
password="123456" #需要创建的数据库用户密码
passwordRoot="123456" #数据库root账号的密码
dbName="bcos_browser"     #需要创建的数据库名
dbIp="192.168.1.100"   #数据库所在机器IP
tomcatpath="/software/tomcat/" #tomcat所在路径

###################### 参数配置结束 #################### 
```

**Comment by songyuanjie** [comment]
![image](https://user-images.githubusercontent.com/7687021/43060342-17ef17f4-8e83-11e8-9ab3-e058e509f12f.png)
mysql已经部署了，查了一下数据库，里边bcos_browser已经创建；出现queryfail这是怎么回事？

**Comment by dwusiq** [comment]
这个应该是后台返回的错误，看下后台什么地方出错了？

**Comment by songyuanjie** [comment]
@dwusiq 后台的js看了一下，看不懂。一入代码深似海，O(∩_∩)O哈哈~

**Comment by songyuanjie** [comment]
![image](https://user-images.githubusercontent.com/7687021/43063087-77188602-8e8d-11e8-8202-f20fde11c084.png)
我部署了一个智能合约，然后调用了一下。再使用test用户登录mysql,查询了一下tb_txnByDay，发现数据库为空，这正常吗？

**Comment by dwusiq** [comment]
不好意思，我刚没说清楚，是看下后台打的日志信息哈

**Comment by songyuanjie** [comment]
@dwusiq 
![image](https://user-images.githubusercontent.com/7687021/43065397-4f72905a-8e94-11e8-95bf-b8a7286ad052.png)apache的后台输出
