### ISSUE TITLE
common.properties中的package.url不存在

### ISSUE THREAD

**Issue by BoCheung** [FISCO-BCOS/fisco-bcos-browser#161]
deploy目录下，common.properties文件中，package.url=https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/FISCO-BCOS/fisco-bcos-browser/releases/download/v2.2.1/fisco-bcos-browser.zip
这个链接是个404

**Comment by mingzhenliu** [comment]
是不是网络有代理，我这里能下载

**Comment by BoCheung** [comment]
现在又可以了。。。确实神奇。我手动改成github的链接搞定了
