### ISSUE TITLE
群组和节点配置希望重新修改

### ISSUE THREAD

**Issue by linbin524** [FISCO-BCOS/fisco-bcos-browser#162]
目前区块链浏览器默认是提供给普通用户查看使用，但是由于群组和节点是直接可以修改，经常会有用户上去修改，导致程序不能用。

区块链浏览器群组和节点配置希望做成后台配置、或者文件配置，如果只是在内网使用的区块链浏览器，没多大使用性，毕竟后台的sdk、webase等都可以实现相关技术对接。

**Comment by mingzhenliu** [comment]
已经支持配置隐藏配置菜单
