### ISSUE TITLE
GovernService.java里面异常处理太随意了，全都是throws Throwable

### ISSUE THREAD

**Issue by string2020** [FISCO-BCOS/fisco-bcos-browser#2]
比如说如下几个方法

public Object getInfoByMethod(String methodName, Object[] params) throws Throwable {

public void handlePendingTransInfo() throws Throwable {

public void handleTransReceiptInfo(String hash) throws Throwable {

public Map<String, Object> handleTransInfo(JSONObject json) throws Throwable {

public void handleBlockInfo(int blockHeight) throws Throwable {

public void handleBlockInfo() throws Throwable {

public void handleBlockChainInfo() throws Throwable {

public void start() throws Throwable {

**Comment by cloudwindworld** [comment]
是个优化的好建议

**Comment by JimmyShi22** [comment]
开发GG正在优化当中了，谢谢！也欢迎你提PR啊

**Comment by fisco-dev** [comment]
fixed
