### ISSUE TITLE
server端代码问题

### ISSUE THREAD

**Issue by artemis-my** [FISCO-BCOS/fisco-bcos-browser#22]
![image](https://user-images.githubusercontent.com/25951395/43431436-65e4edbc-94a0-11e8-8916-7b6d7921fadf.png)
如图，观察到代码已经从原来的org包迁到cn包，为何还保留org包，另外，代码为何要换包呢？

**Comment by liuqikri** [comment]
非常感谢反馈，可能是在合并代码的时候没有删除掉前版本的包，之后会将多余的包删除掉，在次感谢！

**Comment by fisco-dev** [comment]
已建立bugfix分支：https://github.com/FISCO-BCOS/fisco-bcos-browser/tree/bugfix-issue22
在此分支上修复此问题 @liuqikri
