### ISSUE TITLE
区块链浏览器在导入用户配置后只插入了一条tb_user数据未在tb_chain_user表插入数据

### ISSUE THREAD

**Issue by huangmingsir** [FISCO-BCOS/fisco-bcos-browser#222]
区块链浏览器在导入用户配置后只插入了一条tb_user数据未在tb_chain_user表插入数据，此时会导致在“用户配置”列表内能查看到用户数据，而在“区块链信息”-“用户信息”下查看不到用户数据。

**Comment by tumobi** [comment]
tb_chain_user 保存的是产生交易的用户吧

**Comment by Sayou1989** [comment]
> tumobi

是的，链上拉取下来的用户
