### ISSUE TITLE
最新版本是不是方法缺失？导致区块链浏览器未同步最新区块，最新交易？

### ISSUE THREAD

**Issue by she1014** [FISCO-BCOS/fisco-bcos-browser#225]
对应的类：org.bcos.browser.schedule.SchedulerConfig
对应的方法：taskRegistrar.addTriggerTask(() -> schedulerService.handleBlocks(),
                (context) -> new CronTrigger(constants.getCronBlockInfo())
                        .nextExecutionTime(context));
                        
最新的代码没有上面的方法，还是用其它方法代替了？

**Comment by Sayou1989** [comment]
数据同步逻辑修改了，使用了以下jar导出区块和交易数据。添加节点后没拉取到数据的话，可以看一下日志
compile ('com.webank:data-export-sdk:1.7.4'){
        exclude group: 'ch.qos.logback', module: '*'
    }

**Comment by cjo123** [comment]
> export

如果是已经配好节点了 换了数据库就没办法实时更新交易数据了吗
