### ISSUE TITLE
db建表脚本注释格式有误

### ISSUE THREAD

**Issue by artemis-my** [FISCO-BCOS/fisco-bcos-browser#3]
-- 查询块高索引
ALTER TABLE tb_block ADD INDEX index_number (number);
-- 交易表的联合索引
ALTER TABLE tb_transaction ADD INDEX index_number(blockNumber,transactionIndex);

#原注释横杠后缺少空格导致执行失败

**Comment by JimmyShi22** [comment]
是的，谢谢反馈 :)
