### ISSUE TITLE
能够适配一下fisco-bcos2.0版本，我安装了2.0版本的链没有可用的浏览器。

### ISSUE THREAD

**Issue by icejava** [FISCO-BCOS/fisco-bcos-browser#34]
能够适配一下fisco-bcos2.0版本，我安装了2.0版本的链没有可用的浏览器。
监控上报脚本（https://github.com/FISCO-BCOS/fisco-bcos-browser/blob/master/report/README.md） 中的配置与2.0不一致。

**Comment by wheatli** [comment]
有计划在支持了，即将发布，请关注！

**Comment by mingzhenliu** [comment]
dev2.0.0分支支持2.0版本，欢迎体验

**Comment by icejava** [comment]
dev2.0.0版本已经成功搭建，文档质量很好，浏览器效果很好，多谢。
