### ISSUE TITLE
制作了一个 Docker 版本的，方便一键部署，欢迎提意见。

### ISSUE THREAD

**Issue by YoungWilliamZ** [FISCO-BCOS/fisco-bcos-browser#35]
仓库地址：
https://github.com/YoungWilliamZ/fisco-bcos-browser-docker

因为考虑到未来可能在多个服务器部署，因此写了一个 Dockerfile 结合 docker-compose 方便部署。
部署前修改几个关键参数即可自动部署，详见仓库 Readme。

**Comment by mingzhenliu** [comment]
点赞，现在有新版本基于2.0的浏览器。欢迎贡献新的Dockerfile

**Comment by YoungWilliamZ** [comment]
2.0 浏览器更加方便，配置更加简洁。Docker 版本已经更新，一行命令即可部署， 需要的同学请移步 https://github.com/YoungWilliamZ/fisco-bcos-browser-docker/tree/2.0

**Comment by roamingin** [comment]
点赞，感谢您的贡献，您可以添加FISCO BCOS开源社区小助手微信：fiscobcosfan,咱们小助手可以邀请您加入技术交流群，和社区小伙伴们畅聊。
