### ISSUE TITLE
区块链浏览器参数说明

### ISSUE THREAD

**Issue by Tes99t01** [FISCO-BCOS/fisco-bcos-browser#5]
区块链浏览器启动后，可以看到区块有关的交易信息，有没有对区块信息各参数的解释说明文档？比如每个区块JSON的每个key代表什么意思，区块信息如下：
{
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000002000001000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000",
  "totalDifficulty": "0x7f",
  "receiptsRoot": "0x475eeb079cd7e851114f86a667b088959ae413b67cd022f5b315b0655b85b12c",
  "extraData": "0xda8098312e302b2b363035612a524c696e75782f672b2b2f496e74",
  "author": "0x0000000000000000000000000000000000000000",
  "transactions": [
    {
      "blockHash": "0x2ec9865c785c5c73e2827a429259b34c2f36b8ab91ce998120834999ac8b0ba5",
      "input": "0x66c9913900000000000000000000000000000000000000000000000000000000000003e7",
      "randomId": "0x280ea27de0db196090c218018733bcd081bd237ea0ebaa07feda0c7f09d471b",
      "blockNumber": "0x7f",
      "gas": "0x1c9c380",
      "from": "0x79f88c7389714d52b5f68bbca464fa04ffff018f",
      "transactionIndex": "0x0",
      "to": "0x306e04fa1e890dab60f2d54bdb4e1978f4ef47a6",
      "nonce": "0x280ea27de0db196090c218018733bcd081bd237ea0ebaa07feda0c7f09d471b",
      "value": "0x0",
      "hash": "0x55a1eeb6e370022d6cfd34d446889b1e3e8a9009b6cc4ffbb4ae0bbb8344881b",
      "gasPrice": "0x1c9c380"
    }
  ],
  "miner": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x1",
  "gasLimit": "0x77359400",
  "number": "0x7f",
  "gasUsed": "0xe0e8",
  "uncles": [],
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "size": "0x25",
  "transactionsRoot": "0xc2e45c268e9ad0beaf13fd4be093882544bdc0133e06808feb71f639a297a8d2",
  "stateRoot": "0x19d16ea7c2b48e0f51bb813595c76e17dfe12f6dfae41f51bb69446f0ee1f758",
  "genIndex": "0x1",
  "parentHash": "0xce863fe4b0aae61507451c7e1c95fd61230447578cffb1a4072e45f813a86e21",
  "hash": "0x2ec9865c785c5c73e2827a429259b34c2f36b8ab91ce998120834999ac8b0ba5",
  "timestamp": "0x1624946caeb"
}

**Comment by JimmyShi22** [comment]
这里的key基本上和以太坊的一致。
block的key解释：https://ethereumbuilders.gitbooks.io/guide/content/en/ethereum_json_rpc.html#eth_getblockbyhash
transaction的key解释：https://ethereumbuilders.gitbooks.io/guide/content/en/ethereum_json_rpc.html#eth_gettransactionbyhash

**Comment by JimmyShi22** [comment]
摘自：https://ethereumbuilders.gitbooks.io/guide/content/en/ethereum_json_rpc.html

- number: QUANTITY - the block number.
- hash: DATA, 32 Bytes - hash of the block.
- parentHash: DATA, 32 Bytes - hash of the parent block.
- nonce: DATA, 8 Bytes - hash of the generated proof-of-work.
- sha3Uncles: DATA, 32 Bytes - SHA3 of the uncles data in the block.
- logsBloom: DATA, 256 Bytes - the bloom filter for the logs of the block.
- transactionsRoot: DATA, 32 Bytes - the root of the transaction trie of the block
- stateRoot: DATA, 32 Bytes - the root of the final state trie of the block.
- miner: DATA, 20 Bytes - the address of the beneficiary to whom the mining rewards were given.
- difficulty: QUANTITY - integer of the difficulty for this block.
- totalDifficulty: QUANTITY - integer of the total difficulty of the chain until this block.
- extraData: DATA - the "extra data" field of this block.
- size: QUANTITY - integer the size of this block in bytes.
- gasLimit: QUANTITY - the maximum gas allowed in this block.
- gasUsed: QUANTITY - the total used gas by all transactions in this block.
- timestamp: QUANTITY - the unix timestamp for when the block was collated.
- transactions: Array - Array of transaction objects, or 32 Bytes transaction hashes depending on the last given parameter.
- uncles: Array - Array of uncle hashes.
- hash: DATA, 32 Bytes - hash of the transaction.
- nonce: QUANTITY - the number of transactions made by the sender prior to this one.
- blockHash: DATA, 32 Bytes - hash of the block where this transaction was in. null when the transaction is pending.
- blockNumber: QUANTITY - block number where this transaction was in. null when the transaction is pending.
- transactionIndex: QUANTITY - integer of the transactions index position in the block.
- from: DATA, 20 Bytes - address of the sender.
- to: DATA, 20 Bytes - address of the receiver. null when its a contract creation transaction.
- value: QUANTITY - value transferred in Wei.
- gasPrice: QUANTITY - price paid per gas in Wei.
- gas: QUANTITY - gas used.
- input: DATA - the data send along with the transaction.
