### ISSUE TITLE
首页节点端口全部为0

### ISSUE THREAD

**Issue by pengbs** [FISCO-BCOS/fisco-bcos-browser#9]
fisco-bcos-browser搭建成功并且成功运行，但是首页的节点端口那一栏端口全部为0，我是在一台服务器起了很多节点，求帮助
![tim 20180410180852](https://user-images.githubusercontent.com/13148394/38550960-7e16409c-3cea-11e8-9051-5cc90c0c3d33.png)

**Comment by JimmyShi22** [comment]
检查一下fisco-bcos-browser指向的链是否在正常运行，是否能够正常的出块？

**Comment by pengbs** [comment]
感谢回复，指向链接是正常的，而且能够正常出块

**Comment by pengbs** [comment]
你好，我更新到新版1.2该问题还是存在

**Comment by JimmyShi22** [comment]
问题已经定位了，是节点配置文件config.json的配置方法问题。如果在config.json的listenip中配置0.0.0.0，则此处查出来节点端口全部为0。
所以建议给节点的config.json中的listenip配置真实的IP，不推荐配0.0.0.0
