### ISSUE TITLE
建议增加合约事件浏览功能

### ISSUE THREAD

**Issue by JXRow** [FISCO-BCOS/fisco-bcos-browser#97]
目前在区块浏览器里看不到合约事件，不知道合约里面发生了什么，对开发调试和问题排查有很大的障碍，所以希望能有这样的功能。
希望能通过搜索合约，来浏览该合约上发生的事情，包括：
1. emit Transfer(_from, _to, _value);  合约事件
2. require(msg.sender == admin, 'only admin can do this');  异常信息

如果能开放JSON-RPC API接口来获取以上数据，那就更好了

**Comment by mingzhenliu** [comment]
谢谢你的建议，我们排到后续版本

**Comment by mingzhenliu** [comment]
也可以提交pr帮忙我完善这个功能
